<?php

declare(strict_types=1);

if (!defined('_PS_VERSION_')) {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

class extrashippinglabels extends Module
{
    public function __construct()
    {
        $this->name = 'extrashippinglabels';
        $this->tab = 'shipping_logistics';
        $this->version = '1.0.0';
        $this->author = 'extra/';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = ['min' => '9.0.0', 'max' => _PS_VERSION_];
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Shipping Labels');
        $this->description = $this->l('Provides a standard base for managing and displaying shipping labels generated by other modules.');

        $this->tabs = [
            [
                'name' => 'Shipping Labels',
                'class_name' => 'AdminShippingLabel',
                'parent_class_name' => 'AdminParentShipping',
                'visible' => true,
                'icon' => 'local_shipping',
            ],
        ];
    }

    public function install()
    {
        return parent::install() &&
            $this->installSQL() &&
            $this->registerHook('displayAdminOrderMainBottom') &&
            $this->installTab();
    }

    public function uninstall()
    {
        return parent::uninstall() &&
            $this->uninstallSQL() &&
            $this->uninstallTab();
    }

    protected function installSQL()
    {
        $sql = 'CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'shipping_label` (
            `id_shipping_label` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
            `id_order` INT(11) UNSIGNED NOT NULL,
            `tracking_number` VARCHAR(255) NULL,
            `module_name` VARCHAR(64) NULL,
            `label_filepath` VARCHAR(255) NULL,
            `date_add` DATETIME NOT NULL,
            `date_upd` DATETIME NOT NULL,
            PRIMARY KEY (`id_shipping_label`),
            KEY `id_order` (`id_order`),
            KEY `module_name` (`module_name`),
            KEY `tracking_number` (`tracking_number`)
        ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;';

        $result = Db::getInstance()->execute($sql);

        // Trigger hook to notify other modules
        if ($result) {
            Hook::exec('actionShippingLabelsModuleInstalled');
        }

        return $result;
    }

    protected function uninstallSQL()
    {
        $sql = 'DROP TABLE IF EXISTS `' . _DB_PREFIX_ . 'shipping_label`;';
        return Db::getInstance()->execute($sql);
    }

    public function installTab()
    {
        foreach ($this->tabs as $tabData) {
            $tab = new Tab();
            $tab->class_name = $tabData['class_name'];
            $tab->module = $this->name;
            $tab->id_parent = (int)Tab::getIdFromClassName($tabData['parent_class_name']);
            $tab->icon = $tabData['icon'];
            $languages = Language::getLanguages(false);
            foreach ($languages as $lang) {
                $tab->name[$lang['id_lang']] = $this->l($tabData['name']);
            }
            if (!$tab->add()) {
                return false;
            }
        }
        return true;
    }

    public function uninstallTab()
    {
        /** @var \PrestaShopBundle\Entity\Repository\TabRepository $tabRepository */
        $tabRepository = $this->get('prestashop.module.extrashippinglabels.repository');
        $tabs = $tabRepository->findByModule($this->name);
        foreach ($tabs as $tab) {
            $tab = new Tab($tab->getId());
            if (!$tab->delete()) {
                return false;
            }
        }
        return true;
    }

    public function getContent()
    {
        Tools::redirectAdmin($this->context->link->getAdminLink('AdminShippingLabel'));
    }

    public function hookDisplayAdminOrderMainBottom($params)
    {
        if (empty($params['id_order'])) {
            return '';
        }

        try {
            $repository = $this->get('prestashop.module.extrashippinglabels.repository');
            $labels = $repository->getLabelsForOrder((int)$params['id_order']);
        } catch (\Exception $e) {
            $labels = [];
        }

        // For other modules to modify the labels list before display
        Hook::exec('actionModifyShippingLabelsForOrder', [
            'labels' => &$labels,
        ]);

        $router = $this->get('router');
        foreach ($labels as &$label) {
            if (!empty($label['label_filepath'])) {
                $label['download_url'] = $router->generate('ps_extrashippinglabels_labels_download', [
                    'shippingLabelId' => (int)$label['id_shipping_label'],
                ]);
            }
            $label['delete_url'] = $router->generate('ps_extrashippinglabels_labels_delete', [
                'shippingLabelId' => (int)$label['id_shipping_label'],
            ]);
        }

        $this->context->smarty->assign(['shipping_labels' => $labels]);

        return $this->context->smarty->fetch('module:extrashippinglabels/views/templates/hook/order_labels.tpl');
    }
}
