<?php
/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License (AFL 3.0)
 */
declare(strict_types=1);

if (!defined('_PS_VERSION_')) {
    exit;
}

// Needed for install process
require_once __DIR__ . '/vendor/autoload.php';

class extrashippinglabels extends Module
{
    public function __construct()
    {
        $this->name = 'extrashippinglabels';
        $this->tab = 'shipping_logistics';
        $this->version = '1.0.0';
        $this->author = 'PrestaShop';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = ['min' => '9.0.0', 'max' => _PS_VERSION_];
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Shipping Labels');
        $this->description = $this->l('Provides a standard base for managing and displaying shipping labels generated by other modules.');

        $this->tabs = [
            [
                'name' => 'Shipping Labels',
                'class_name' => 'AdminShippingLabel',
                'parent_class_name' => 'AdminParentShipping',
                'visible' => true,
                'icon' => 'local_shipping',
            ],
        ];
    }

    public function install()
    {
        return parent::install() &&
            $this->installSQL() &&
            $this->registerHook('displayAdminOrderMainBottom') &&
            $this->installTab();
    }

    public function uninstall()
    {
        return parent::uninstall() &&
            $this->uninstallSQL() &&
            $this->uninstallTab();
    }

    protected function installSQL()
    {
        $sql = 'CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'shipping_label` (
            `id_shipping_label` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
            `id_order` INT(11) UNSIGNED NOT NULL,
            `tracking_number` VARCHAR(255) NULL,
            `module_name` VARCHAR(64) NOT NULL,
            `label_filepath` VARCHAR(255) NULL,
            `date_add` DATETIME NOT NULL,
            `date_upd` DATETIME NOT NULL,
            PRIMARY KEY (`id_shipping_label`),
            KEY `id_order` (`id_order`),
            KEY `module_name` (`module_name`)
        ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8;';

        return Db::getInstance()->execute($sql);
    }

    protected function uninstallSQL()
    {
        $sql = 'DROP TABLE IF EXISTS `' . _DB_PREFIX_ . 'shipping_label`;';
        return Db::getInstance()->execute($sql);
    }

    public function installTab()
    {
        foreach ($this->tabs as $tabData) {
            $tab = new Tab();
            $tab->class_name = $tabData['class_name'];
            $tab->module = $this->name;
            $tab->id_parent = (int)Tab::getIdFromClassName($tabData['parent_class_name']);
            $tab->icon = $tabData['icon'];
            $languages = Language::getLanguages(false);
            foreach ($languages as $lang) {
                $tab->name[$lang['id_lang']] = $this->l($tabData['name']);
            }
            if (!$tab->add()) {
                return false;
            }
        }
        return true;
    }

    public function uninstallTab()
    {
        foreach ($this->tabs as $tabData) {
            $id_tab = (int)Tab::getIdFromClassName($tabData['class_name']);
            if ($id_tab) {
                $tab = new Tab($id_tab);
                if (!$tab->delete()) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Redirect to the modern Symfony controller
     */
    public function getContent()
    {
        Tools::redirectAdmin(
            $this->context->link->getAdminLink('AdminShippingLabel')
        );
    }

    /**
     * Hook to display shipping labels on the order view page.
     */
    public function hookDisplayAdminOrderMainBottom($params)
    {
        if (empty($params['id_order'])) {
            return '';
        }

        $labels = $this->getLabelsForOrder((int)$params['id_order']);

        if (empty($labels)) {
            return '';
        }

        // Expose a hook for other modules to modify the labels list before display
        Hook::exec('actionModifyShippingLabelsForOrder', [
            'labels' => &$labels,
        ]);

        $this->context->smarty->assign([
            'shipping_labels' => $labels,
        ]);

        return $this->display(__FILE__, 'views/templates/hook/order_labels.html.twig');
    }

    /**
     * Get labels for a given order ID.
     * This could be moved to a dedicated ObjectModel or Repository class.
     *
     * @param int $id_order
     * @return array
     */
    private function getLabelsForOrder(int $id_order): array
    {
        $query = new DbQuery();
        $query->select('*');
        $query->from('shipping_label');
        $query->where('id_order = ' . $id_order);

        $results = Db::getInstance()->executeS($query);

        if (!$results) {
            return [];
        }

        // Allow other modules to potentially enrich the label data (e.g., add a direct download link)
        foreach ($results as &$label) {
            Hook::exec('actionGetShippingLabelData', [
                'label' => &$label,
            ]);
        }

        return $results;
    }
}
