<?php

declare(strict_types=1);

if (!defined('_PS_VERSION_')) {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

class extrashippinglabels extends Module
{
    public function __construct()
    {
        $this->name = 'extrashippinglabels';
        $this->tab = 'shipping_logistics';
        $this->version = '1.0.0';
        $this->author = 'extra/';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = ['min' => '9.0.0', 'max' => _PS_VERSION_];
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Shipping labels');
        $this->description = $this->l('Provides a standard base for managing and displaying shipping labels generated by other modules.');

        $this->tabs = [
            [
                'name' => 'Shipping Labels',
                'class_name' => 'AdminShippingLabel',
                'parent_class_name' => 'AdminParentShipping',
                'visible' => true,
                'icon' => 'local_shipping',
            ],
        ];
    }

    public function install()
    {
        return parent::install() &&
            $this->installSQL() &&
            $this->registerHook('displayAdminOrderTabLink') &&
            $this->registerHook('displayAdminOrderTabContent') &&
            $this->registerHook('actionOrderGridDefinitionModifier') &&
            $this->registerHook('actionOrderGenerateShippingLabel') &&
            $this->registerHook('displayBackOfficeFooter') &&
            $this->installTab();
    }

    public function uninstall()
    {
        return parent::uninstall() &&
            $this->uninstallSQL() &&
            $this->unregisterHook('displayAdminOrderTabLink') &&
            $this->unregisterHook('displayAdminOrderTabContent') &&
            $this->unregisterHook('actionOrderGridDefinitionModifier') &&
            $this->unregisterHook('actionOrderGenerateShippingLabel') &&
            $this->uninstallTab();
    }

    protected function installSQL()
    {
        $sql = 'CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'shipping_label` (
            `id_shipping_label` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
            `id_order` INT(11) UNSIGNED NOT NULL,
            `tracking_number` VARCHAR(255) NULL,
            `module_name` VARCHAR(64) NULL,
            `label_filepath` VARCHAR(255) NULL,
            `date_add` DATETIME NOT NULL,
            `date_upd` DATETIME NOT NULL,
            PRIMARY KEY (`id_shipping_label`),
            KEY `id_order` (`id_order`),
            KEY `module_name` (`module_name`),
            KEY `tracking_number` (`tracking_number`)
        ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;';

        $result = Db::getInstance()->execute($sql);

        // Trigger hook to notify other modules
        if ($result) {
            Hook::exec('actionShippingLabelsModuleInstalled');
        }

        return $result;
    }

    protected function uninstallSQL()
    {
        $sql = 'DROP TABLE IF EXISTS `' . _DB_PREFIX_ . 'shipping_label`;';
        return Db::getInstance()->execute($sql);
    }

    public function installTab()
    {
        foreach ($this->tabs as $tabData) {
            $tab = new Tab();
            $tab->class_name = $tabData['class_name'];
            $tab->module = $this->name;
            $tab->id_parent = (int)Tab::getIdFromClassName($tabData['parent_class_name']);
            $tab->icon = $tabData['icon'];
            $languages = Language::getLanguages(false);
            foreach ($languages as $lang) {
                $tab->name[$lang['id_lang']] = $this->l($tabData['name']);
            }
            if (!$tab->add()) {
                return false;
            }
        }
        return true;
    }

    public function uninstallTab()
    {
        foreach ($this->tabs as $tabData) {
            $tabId = (int) Tab::getIdFromClassName($tabData['class_name']);
            if ($tabId) {
                $tab = new Tab($tabId);
                if (!$tab->delete()) {
                    return false;
                }
            }
        }
        return true;
    }

    public function getContent()
    {
        Tools::redirectAdmin($this->context->link->getAdminLink('AdminShippingLabel'));
    }

    public function hookDisplayAdminOrderTabLink($params)
    {
        if (empty($params['id_order'])) {
            return '';
        }

        try {
            $repository = $this->get('prestashop.module.extrashippinglabels.repository');
            $labels = $repository->getLabelsForOrder((int)$params['id_order']);
        } catch (\Exception $e) {
            $labels = [];
        }

        $this->context->smarty->assign([
            'labels_count' => count($labels),
        ]);

        return $this->context->smarty->fetch('module:extrashippinglabels/views/templates/hook/tab_link.tpl');
    }

    public function hookDisplayAdminOrderTabContent($params)
    {
        if (empty($params['id_order'])) {
            return '';
        }

        try {
            $repository = $this->get('prestashop.module.extrashippinglabels.repository');
            $labels = $repository->getLabelsForOrder((int)$params['id_order']);
        } catch (\Exception $e) {
            $labels = [];
        }

        // For other modules to modify the labels list before display
        Hook::exec('actionModifyShippingLabelsForOrder', [
            'labels' => &$labels,
        ]);

        $router = $this->get('router');
        $orderViewUrl = $router->generate('admin_orders_view', ['orderId' => (int)$params['id_order']]);

        foreach ($labels as &$label) {
            if (!empty($label['label_filepath'])) {
                $label['download_url'] = $router->generate('ps_extrashippinglabels_labels_download', [
                    'shippingLabelId' => (int)$label['id_shipping_label'],
                ]);
            }
            $label['delete_url'] = $router->generate('ps_extrashippinglabels_labels_delete', [
                'shippingLabelId' => (int)$label['id_shipping_label'],
                'redirect' => $orderViewUrl,
            ]);

            // Format date for display
            $dateAdd = new \DateTime($label['date_add']);
            $label['date_formatted'] = $dateAdd->format('d/m/Y H:i');
        }

        $this->context->smarty->assign([
            'shipping_labels' => $labels,
            'id_order' => (int)$params['id_order'],
        ]);

        return $this->context->smarty->fetch('module:extrashippinglabels/views/templates/hook/tab_content.tpl');
    }

    /**
     * Hook to add a bulk action to the orders grid.
     *
     * @param array $params
     */
    public function hookActionOrderGridDefinitionModifier(array &$params)
    {
        /** @var \PrestaShop\PrestaShop\Core\Grid\Definition\GridDefinitionInterface $definition */
        $definition = $params['definition'];

        $definition
            ->getBulkActions()
            ->add(
                (new PrestaShop\PrestaShop\Core\Grid\Action\Bulk\Type\SubmitBulkAction('generate_extra_shipping_labels'))
                    ->setName($this->l('Generate shipping labels'))
                    ->setOptions([
                        'submit_route' => 'ps_extrashippinglabels_labels_generate_bulk',
                    ])
            )
            ->add(
                (new PrestaShop\PrestaShop\Core\Grid\Action\Bulk\Type\SubmitBulkAction('download_extra_shipping_labels'))
                    ->setName($this->l('Download shipping labels'))
                    ->setOptions([
                        'submit_route' => 'ps_extrashippinglabels_labels_download_bulk',
                    ])
            )
            ->add(
                (new PrestaShop\PrestaShop\Core\Grid\Action\Bulk\Type\ButtonBulkAction('print_extra_shipping_labels'))
                    ->setName($this->l('Print shipping labels'))
                    ->setOptions([
                        'class' => 'js-print-shipping-labels-bulk-action',
                        'attributes' => [
                            'data-print-url' => $this->get('router')->generate('ps_extrashippinglabels_labels_print_bulk'),
                        ],
                    ])
            );
    }

    /**
     * Custom hook for generating a shipping label for a specific order.
     * This hook is intended to be triggered by this module but implemented by other modules.
     *
     * @param array $params
     */
    public function hookActionOrderGenerateShippingLabel(array $params)
    {
        // This is a custom hook, other modules should implement their logic here.
        // The module triggering this hook doesn't need to do anything.
    }

    /**
     * Hook to inject the print modal and JavaScript on the orders list page.
     *
     * @param array $params
     * @return string
     */
    public function hookDisplayBackOfficeFooter(array $params)
    {
        // Only display on orders list page
        $controller = Tools::getValue('controller');

        // Get current route from request stack
        $route = null;
        try {
            $requestStack = $this->get('request_stack');
            $currentRequest = $requestStack->getCurrentRequest();
            if ($currentRequest) {
                $route = $currentRequest->attributes->get('_route');
            }
        } catch (\Exception $e) {
            // Service not available
        }

        if ($controller !== 'AdminOrders' && $route !== 'admin_orders_index') {
            return '';
        }

        $router = $this->get('router');
        $twig = $this->get('twig');

        // Render the modal
        $modalHtml = $twig->render('@Modules/extrashippinglabels/views/templates/admin/print_modal.html.twig', [
            'print_url' => $router->generate('ps_extrashippinglabels_labels_print_bulk'),
        ]);

        // Add JavaScript
        $jsPath = $this->getPathUri() . 'views/js/print_shipping_labels.js';

        return $modalHtml . '<script src="' . $jsPath . '"></script>';
    }
}
